"C:\Qt\bin\moc.exe"  blocks.h -o "moc/moc_blocks.cpp"
"C:\Qt\bin\moc.exe"  Player.h -o "moc/moc_palyer.cpp"
"C:\Qt\bin\moc.exe"  screen.h -o "moc/moc_screen.cpp"
"C:\Qt\bin\moc.exe"  VirtScreen.h -o "moc/moc_VirtScreen.cpp"
"C:\Qt\bin\moc.exe"  i_thread.h -o "moc/moc_i_thread.cpp"
"C:\Qt\bin\moc.exe"  world.h -o "moc/moc_world.cpp"
"C:\Qt\bin\moc.exe"  thread.h -o "moc/moc_thread.cpp"
"C:\Qt\bin\moc.exe"  ShredStorage.h -o "moc/moc_shred_storage.cpp"
"C:\Qt\bin\moc.exe"  Active.h -o "moc/moc_active.cpp"
"C:\Qt\bin\moc.exe"  Dwarf.h -o "moc/moc_dwarf.cpp"
"C:\Qt\bin\moc.exe"  Animal.h -o "moc/moc_animal.cpp"
pause